name: Continuous Integration

on:
  # push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions: write-all

env:
  ECR_REPOSITORY: data-plaform/ml/ad

jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Run tests
          run: |
            echo "Running unit tests..."
            # Add your test commands here, e.g., npm test, pytest, etc.

  release-management:
    name: Release management
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
    steps:
      - name: Generate Release Version
        id: generate-version
        uses: amsrun/template/.github/actions/generate-version@main
        # with:
        #   release: true

    #uses: amsrun/template/.github/workflows/release-management.yml@main

  docker:
    name: Build and Push Docker Image
    needs: [release-management]
    runs-on: ubuntu-latest
    environment: development
    outputs:
      image_tag: ${{ steps.build-image.outputs.image_tag }}
    defaults:
      run:
        shell: bash
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-2"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # For Pointing to dev account otherwise ECR login defaults to Infra account
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_DEPLOYMENT_ROLE }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, test, tag, and push service image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: "ci-${{ github.sha }}"
        run: |
          docker build -f ./Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG          
          echo "image_tag=$(echo $IMAGE_TAG)" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy AWS infrastructure
    needs: [release-management, unit-test]
    runs-on: ubuntu-latest
    # environment: production
    steps:
      - name: Display Release Version
        run: |
          echo "Release version: ${{ needs.release-management.outputs.version }}"
          echo "This version can be used for tagging, creating releases, etc."

  
  post-release:
    name: Post-release management
    needs: [release-management, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Git tagging w/ release
        uses: amsrun/template/.github/actions/create-release@main
        with:
          tag: ${{ needs.release-management.outputs.version }}
          release: true

  debug:
    name: Debug
    needs: [release-management, unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Display Release Version
        run: |
          echo "Release version: ${{ needs.release-management.outputs.version }}"
          echo "This version can be used for tagging, creating releases, etc."
