name: Continuous Integration

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash


jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Run tests
          run: |
            echo "Running unit tests..."
            # Add your test commands here, e.g., npm test, pytest, etc.

  release-management:
    name: Release management
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
    steps:
      - name: Generate Release Version
        id: generate-version
        uses: amsrun/template/.github/actions/generate-version@main
        with:
          release: true

    #uses: amsrun/template/.github/workflows/release-management.yml@main

  deploy:
    name: Debug
    needs: [release-management, unit-test]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Display Release Version
        run: |
          echo "Release version: ${{ needs.release-management.outputs.version }}"
          echo "This version can be used for tagging, creating releases, etc."

  
  post-release:
    name: Debug
    needs: [release-management, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Git tagging
        uses: amsrun/template/.github/actions/git-tag@main
        with:
          tag: ${{ needs.release-management.outputs.version }}

  
  debug:
    name: Debug
    needs: [release-management, unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Display Release Version
        run: |
          echo "Release version: ${{ needs.release-management.outputs.version }}"
          echo "This version can be used for tagging, creating releases, etc."
