name: Deployment

on:
  workflow_call:
    inputs:
      environment:
        description: Deployment environment to target
        required: true
        type: string
      terraform_directory:
        description: Terraform working directory
        required: false
        type: string
        default: "infrastructure"
    secrets:
      AWS_ACCESS_KEY_ID:
        description: AWS access key ID with permissions to deploy infrastructure and applications
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: AWS secret access key with permissions to deploy infrastructure and applications
        required: true

permissions: write-all

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# Due to the approval configured at the environment level, tasks that cannot run in parallel will need to be grouped into a single job.

jobs:
  aws:
    name: AWS
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        # with:
        #   aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   aws-region: ${{ vars.AWS_REGION }}
      - name: Mock deployment step
        run: aws sts get-caller-identity --output json
      # - name: Deploy infrastructure with Terraform
      #   if: ${{ false }}
      #   uses: your-org/your-terraform-composite-action@your-ref
      #   with:
      #     environment: ${{ inputs.target_environment }}
      #     aws_region: ${{ inputs.aws_region }}
      #     terraform_directory: ${{ inputs.terraform_directory }}

  ecr-tags:
    name: ECR image tags
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update tags on existing ECR image
        uses: amsrun/template/actions/ecr-tag@main
        with:
          repository: ${{ vars.ECR_REPOSITORY }}
          source-tag: ${{ github.sha }}
          tags: ${{ inputs.environment }}

  additional-deployment-tasks:
    name: Additional deployment tasks (placeholder)
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Placeholder
        run: echo "Add additional deployment tasks here"