name: Experiment

on:
  push:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - name: git tagging
        uses: amsrun/template/.github/actions/git-tag@main
