name: Call Test Environments Workflow

on:
  workflow_dispatch:
    inputs:
      custom_message:
        description: 'Custom message to pass'
        required: false
        type: string
        default: 'Testing environment variables'

jobs:
  release-management:
    name: Release management
    uses: amsrun/template/.github/workflows/release-management.yml@main

  call-workflow:
    name: Call reusable workflow
    needs: release-management
    uses: amsrun/template/.github/workflows/test.yml@main
    with:
      message: ${{ inputs.custom_message }}

  debug:
    needs: release-management
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Display Release Version
        run: |
          echo "Release version: ${{ needs.release-management.outputs.release-version }}"
          echo "This version can be used for tagging, creating releases, etc."

  stg:
    name: Deploy to Staging
    needs: call-workflow
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Yay!
        run: pwd
  

