name: Call Test Environments Workflow

on:
  workflow_dispatch:
    inputs:
      custom_message:
        description: 'Custom message to pass'
        required: false
        type: string
        default: 'Testing environment variables'
  push:

jobs:
  call-reusable-workflow:
    name: Call reusable workflow
    uses: amsrun/template/.github/workflows/test-environments.yml@main
    with:
      environment: staging
      message: ${{ inputs.custom_message }}
